runtime: nodejs
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4

env_variables:
  SQL_USER: root
  SQL_PASSWORD: "store@loud9"
  SQL_DATABASE: shopify_db
  INSTANCE_CONNECTION_NAME: astral-gateway-370305:us-central1:cloud9

beta_settings:
  cloud_sql_instances: astral-gateway-370305:us-central1:cloud9
